default: &default
  secret_key_base: 'yrwiuyeryuiweyiuri12387987921789217987982137982iuqeuiqiuoqweuioewquioeqwio'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
